# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Enable AndroidX (Mandatory for modern Android dependencies)
android.useAndroidX=true

# Set official Kotlin code style
kotlin.code.style=official
